package com.springboot.forum.entity;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.clientid
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    private Integer clientid;

    public Client(Integer clientid, String clientname, String clientpwd, String clientemail, String clientright,
			String logintime) {
		super();
		this.clientid = clientid;
		this.clientname = clientname;
		this.clientpwd = clientpwd;
		this.clientemail = clientemail;
		this.clientright = clientright;
		this.logintime = logintime;
	}

	public Client(String clientname, String clientpwd) {
		super();
		this.clientname = clientname;
		this.clientpwd = clientpwd;
	}

	public Client() {
		super();
	}

	public Client(String clientname, String clientpwd, String clientemail) {
		super();
		this.clientname = clientname;
		this.clientpwd = clientpwd;
		this.clientemail = clientemail;
	}

	@Override
	public String toString() {
		return "Client [clientid=" + clientid + ", clientname=" + clientname + ", clientpwd=" + clientpwd
				+ ", clientemail=" + clientemail + ", clientright=" + clientright + ", logintime=" + logintime + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.clientname
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    private String clientname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.clientpwd
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    private String clientpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.clientemail
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    private String clientemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.clientright
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    private String clientright;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.logintime
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    private String logintime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clientid
     *
     * @return the value of client.clientid
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clientid
     *
     * @param clientid the value for client.clientid
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clientname
     *
     * @return the value of client.clientname
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clientname
     *
     * @param clientname the value for client.clientname
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public void setClientname(String clientname) {
        this.clientname = clientname == null ? null : clientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clientpwd
     *
     * @return the value of client.clientpwd
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public String getClientpwd() {
        return clientpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clientpwd
     *
     * @param clientpwd the value for client.clientpwd
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public void setClientpwd(String clientpwd) {
        this.clientpwd = clientpwd == null ? null : clientpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clientemail
     *
     * @return the value of client.clientemail
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public String getClientemail() {
        return clientemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clientemail
     *
     * @param clientemail the value for client.clientemail
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public void setClientemail(String clientemail) {
        this.clientemail = clientemail == null ? null : clientemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clientright
     *
     * @return the value of client.clientright
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public String getClientright() {
        return clientright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clientright
     *
     * @param clientright the value for client.clientright
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public void setClientright(String clientright) {
        this.clientright = clientright == null ? null : clientright.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.logintime
     *
     * @return the value of client.logintime
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public String getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.logintime
     *
     * @param logintime the value for client.logintime
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public void setLogintime(String logintime) {
        this.logintime = logintime == null ? null : logintime.trim();
    }
}