package com.springboot.forum.entity;

public class Logintime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logintime.timeid
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    private Integer timeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logintime.clientid
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    private Integer clientid;

    public Logintime() {
		super();
	}

	public Logintime(Integer timeid, Integer clientid, String logintime) {
		super();
		this.timeid = timeid;
		this.clientid = clientid;
		this.logintime = logintime;
	}

	@Override
	public String toString() {
		return "Logintime [timeid=" + timeid + ", clientid=" + clientid + ", logintime=" + logintime + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logintime.logintime
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    private String logintime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logintime.timeid
     *
     * @return the value of logintime.timeid
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public Integer getTimeid() {
        return timeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logintime.timeid
     *
     * @param timeid the value for logintime.timeid
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public void setTimeid(Integer timeid) {
        this.timeid = timeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logintime.clientid
     *
     * @return the value of logintime.clientid
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logintime.clientid
     *
     * @param clientid the value for logintime.clientid
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logintime.logintime
     *
     * @return the value of logintime.logintime
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public String getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logintime.logintime
     *
     * @param logintime the value for logintime.logintime
     *
     * @mbg.generated Thu Sep 24 17:23:48 CST 2020
     */
    public void setLogintime(String logintime) {
        this.logintime = logintime == null ? null : logintime.trim();
    }
}